vertex:
  project:
    id: project-8d79f0d9-c8dd-4f76-ad1
  dataStore:
    id: datastore-catalin_1770280012387
    location: eu
  model:
    name: gemini-2.5-flash
    location: europe-central2
    temperature: 0.2
    maxOutputTokens: 32768