vertex:
  project:
    id: magicode-486907
  dataStore:
    id: magicode-datastore_1770626336218
    location: global
  model:
    name: gemini-2.5-flash
    location: europe-central2
    temperature: 0.2
    maxOutputTokens: 32768